// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJOrxAfhe9_vQT6eTPkS5EbwGSMi4FrMs',
    appId: '1:1010141770300:web:0ea04cda687c4806c9c939',
    messagingSenderId: '1010141770300',
    projectId: 'chat-app-2c62d',
    authDomain: 'chat-app-2c62d.firebaseapp.com',
    storageBucket: 'chat-app-2c62d.firebasestorage.app',
    measurementId: 'G-3N408RLBJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUZoAuN6LAHb11QMJu-euYb3p1GkMHHSY',
    appId: '1:1010141770300:android:3bfc02db3ba80c2dc9c939',
    messagingSenderId: '1010141770300',
    projectId: 'chat-app-2c62d',
    storageBucket: 'chat-app-2c62d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARxWYQeVYZj_hWBRvMinaq6S8b5mac7xA',
    appId: '1:1010141770300:ios:0fb4815391ce48b6c9c939',
    messagingSenderId: '1010141770300',
    projectId: 'chat-app-2c62d',
    storageBucket: 'chat-app-2c62d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARxWYQeVYZj_hWBRvMinaq6S8b5mac7xA',
    appId: '1:1010141770300:ios:0fb4815391ce48b6c9c939',
    messagingSenderId: '1010141770300',
    projectId: 'chat-app-2c62d',
    storageBucket: 'chat-app-2c62d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJOrxAfhe9_vQT6eTPkS5EbwGSMi4FrMs',
    appId: '1:1010141770300:web:8886c9dd49ceddffc9c939',
    messagingSenderId: '1010141770300',
    projectId: 'chat-app-2c62d',
    authDomain: 'chat-app-2c62d.firebaseapp.com',
    storageBucket: 'chat-app-2c62d.firebasestorage.app',
    measurementId: 'G-QR72262L0N',
  );
}
